[package]
name = "apihasher-procs"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
proc-macro2 = "1.0.86"
quote = "1.0.37"
rand = "0.8.5"
syn = "2.0.76"

[lib]
proc-macro = true
